### ISSUE TITLE
How is the detector trained?

### ISSUE THREAD

**Issue by Yijia-Chen** [s-nandi/carla-car-detection#3]

**Comment by s-nandi** [comment]
I took the pretrained faster_rcnn_inception_v2_coco model from [Tensorflow's detection model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md), and trained it further on the labeled data provided in [Carla-Object-Detection-Dataset](https://github.com/DanielHfnr/Carla-Object-Detection-Dataset). The number following "detectors-" (ex. detectors-40264) denotes the number of training iterations for the detector at hand.

If you are interested in replicating the process yourself, the [Training Custom Detector](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html) section of the object detection API docs might be of use.

**Comment by Yijia-Chen** [comment]
Got it, thanks!
