### ISSUE TITLE
    self.od_graph_def.ParseFromString(self.serialized_graph) google.protobuf.message.DecodeError: Error parsing message

### ISSUE THREAD

**Issue by guilherme-mendes** [s-nandi/carla-car-detection#5]
Any solution?
Thank you!

**Comment by saujasn** [comment]
This was an issue for one of my co-contributors. They resolved it by setting up git-lfs properly, and switching to the following environment:

Ubuntu 16.04
Tensorflow 1.14 (with CUDA 10.2)
Python 3.6

Let me know if that helps!

**Comment by guilherme-mendes** [comment]
Solved my problem!
